#!/usr/bin/env roundup

describe "diff-line file1 file2"

t() {
  test "$(../diff-line ./fixtures/$1 ./fixtures/$2)" "=" "$3"
}

it_prints_usage_message() {
  [[ "$(../diff-line)" == "Usage:"* ]] && foo=1
  test -n "$foo"
  [[ "$(../diff-line foo)" == "Usage:"* ]] && bar=1
  test -n "$bar"
}

it_test_0_empty() {
  t "0_empty" "0_empty" ""
  t "0_empty" "1_bar" "1"
  t "0_empty" "1_foo" "1"
  t "0_empty" "1_n" "1"
  t "0_empty" "2_bar_bar" "1"
  t "0_empty" "2_bar_foo" "1"
  t "0_empty" "2_bar_n" "1"
  t "0_empty" "2_foo_bar" "1"
  t "0_empty" "2_foo_foo" "1"
  t "0_empty" "2_foo_n" "1"
  t "0_empty" "2_n_bar" "1"
  t "0_empty" "2_n_foo" "1"
  t "0_empty" "2_n_n" "1"
  t "0_empty" "3_n_bar_bar" "1"
  t "0_empty" "3_n_bar_foo" "1"
  t "0_empty" "3_n_bar_n" "1"
  t "0_empty" "3_n_foo_bar" "1"
  t "0_empty" "3_n_foo_foo" "1"
  t "0_empty" "3_n_foo_n" "1"
  t "0_empty" "3_n_n_bar" "1"
  t "0_empty" "3_n_n_foo" "1"
  t "0_empty" "3_n_n_n" "1"
}

it_test_1_bar() {
  t "1_bar" "0_empty" "1"
  t "1_bar" "1_bar" ""
  t "1_bar" "1_foo" "1"
  t "1_bar" "1_n" "1"
  t "1_bar" "2_bar_bar" "1"
  t "1_bar" "2_bar_foo" "1"
  t "1_bar" "2_bar_n" "1"
  t "1_bar" "2_foo_bar" "1"
  t "1_bar" "2_foo_foo" "1"
  t "1_bar" "2_foo_n" "1"
  t "1_bar" "2_n_bar" "1"
  t "1_bar" "2_n_foo" "1"
  t "1_bar" "2_n_n" "1"
  t "1_bar" "3_n_bar_bar" "1"
  t "1_bar" "3_n_bar_foo" "1"
  t "1_bar" "3_n_bar_n" "1"
  t "1_bar" "3_n_foo_bar" "1"
  t "1_bar" "3_n_foo_foo" "1"
  t "1_bar" "3_n_foo_n" "1"
  t "1_bar" "3_n_n_bar" "1"
  t "1_bar" "3_n_n_foo" "1"
  t "1_bar" "3_n_n_n" "1"
}

it_test_1_foo() {
  t "1_foo" "0_empty" "1"
  t "1_foo" "1_bar" "1"
  t "1_foo" "1_foo" ""
  t "1_foo" "1_n" "1"
  t "1_foo" "2_bar_bar" "1"
  t "1_foo" "2_bar_foo" "1"
  t "1_foo" "2_bar_n" "1"
  t "1_foo" "2_foo_bar" "1"
  t "1_foo" "2_foo_foo" "1"
  t "1_foo" "2_foo_n" "1"
  t "1_foo" "2_n_bar" "1"
  t "1_foo" "2_n_foo" "1"
  t "1_foo" "2_n_n" "1"
  t "1_foo" "3_n_bar_bar" "1"
  t "1_foo" "3_n_bar_foo" "1"
  t "1_foo" "3_n_bar_n" "1"
  t "1_foo" "3_n_foo_bar" "1"
  t "1_foo" "3_n_foo_foo" "1"
  t "1_foo" "3_n_foo_n" "1"
  t "1_foo" "3_n_n_bar" "1"
  t "1_foo" "3_n_n_foo" "1"
  t "1_foo" "3_n_n_n" "1"
}

it_test_1_n() {
  t "1_n" "0_empty" "1"
  t "1_n" "1_bar" "1"
  t "1_n" "1_foo" "1"
  t "1_n" "1_n" ""
  t "1_n" "2_bar_bar" "1"
  t "1_n" "2_bar_foo" "1"
  t "1_n" "2_bar_n" "1"
  t "1_n" "2_foo_bar" "1"
  t "1_n" "2_foo_foo" "1"
  t "1_n" "2_foo_n" "1"
  t "1_n" "2_n_bar" "2"
  t "1_n" "2_n_foo" "2"
  t "1_n" "2_n_n" "2"
  t "1_n" "3_n_bar_bar" "2"
  t "1_n" "3_n_bar_foo" "2"
  t "1_n" "3_n_bar_n" "2"
  t "1_n" "3_n_foo_bar" "2"
  t "1_n" "3_n_foo_foo" "2"
  t "1_n" "3_n_foo_n" "2"
  t "1_n" "3_n_n_bar" "2"
  t "1_n" "3_n_n_foo" "2"
  t "1_n" "3_n_n_n" "2"
}

it_test_2_bar_bar() {
  t "2_bar_bar" "0_empty" "1"
  t "2_bar_bar" "1_bar" "1"
  t "2_bar_bar" "1_foo" "1"
  t "2_bar_bar" "1_n" "1"
  t "2_bar_bar" "2_bar_bar" ""
  t "2_bar_bar" "2_bar_foo" "2"
  t "2_bar_bar" "2_bar_n" "2"
  t "2_bar_bar" "2_foo_bar" "1"
  t "2_bar_bar" "2_foo_foo" "1"
  t "2_bar_bar" "2_foo_n" "1"
  t "2_bar_bar" "2_n_bar" "1"
  t "2_bar_bar" "2_n_foo" "1"
  t "2_bar_bar" "2_n_n" "1"
  t "2_bar_bar" "3_n_bar_bar" "1"
  t "2_bar_bar" "3_n_bar_foo" "1"
  t "2_bar_bar" "3_n_bar_n" "1"
  t "2_bar_bar" "3_n_foo_bar" "1"
  t "2_bar_bar" "3_n_foo_foo" "1"
  t "2_bar_bar" "3_n_foo_n" "1"
  t "2_bar_bar" "3_n_n_bar" "1"
  t "2_bar_bar" "3_n_n_foo" "1"
  t "2_bar_bar" "3_n_n_n" "1"
}

it_test_2_bar_foo() {
  t "2_bar_foo" "0_empty" "1"
  t "2_bar_foo" "1_bar" "1"
  t "2_bar_foo" "1_foo" "1"
  t "2_bar_foo" "1_n" "1"
  t "2_bar_foo" "2_bar_bar" "2"
  t "2_bar_foo" "2_bar_foo" ""
  t "2_bar_foo" "2_bar_n" "2"
  t "2_bar_foo" "2_foo_bar" "1"
  t "2_bar_foo" "2_foo_foo" "1"
  t "2_bar_foo" "2_foo_n" "1"
  t "2_bar_foo" "2_n_bar" "1"
  t "2_bar_foo" "2_n_foo" "1"
  t "2_bar_foo" "2_n_n" "1"
  t "2_bar_foo" "3_n_bar_bar" "1"
  t "2_bar_foo" "3_n_bar_foo" "1"
  t "2_bar_foo" "3_n_bar_n" "1"
  t "2_bar_foo" "3_n_foo_bar" "1"
  t "2_bar_foo" "3_n_foo_foo" "1"
  t "2_bar_foo" "3_n_foo_n" "1"
  t "2_bar_foo" "3_n_n_bar" "1"
  t "2_bar_foo" "3_n_n_foo" "1"
  t "2_bar_foo" "3_n_n_n" "1"
}

it_test_2_bar_n() {
  t "2_bar_n" "0_empty" "1"
  t "2_bar_n" "1_bar" "1"
  t "2_bar_n" "1_foo" "1"
  t "2_bar_n" "1_n" "1"
  t "2_bar_n" "2_bar_bar" "2"
  t "2_bar_n" "2_bar_foo" "2"
  t "2_bar_n" "2_bar_n" ""
  t "2_bar_n" "2_foo_bar" "1"
  t "2_bar_n" "2_foo_foo" "1"
  t "2_bar_n" "2_foo_n" "1"
  t "2_bar_n" "2_n_bar" "1"
  t "2_bar_n" "2_n_foo" "1"
  t "2_bar_n" "2_n_n" "1"
  t "2_bar_n" "3_n_bar_bar" "1"
  t "2_bar_n" "3_n_bar_foo" "1"
  t "2_bar_n" "3_n_bar_n" "1"
  t "2_bar_n" "3_n_foo_bar" "1"
  t "2_bar_n" "3_n_foo_foo" "1"
  t "2_bar_n" "3_n_foo_n" "1"
  t "2_bar_n" "3_n_n_bar" "1"
  t "2_bar_n" "3_n_n_foo" "1"
  t "2_bar_n" "3_n_n_n" "1"
}

it_test_2_foo_bar() {
  t "2_foo_bar" "0_empty" "1"
  t "2_foo_bar" "1_bar" "1"
  t "2_foo_bar" "1_foo" "1"
  t "2_foo_bar" "1_n" "1"
  t "2_foo_bar" "2_bar_bar" "1"
  t "2_foo_bar" "2_bar_foo" "1"
  t "2_foo_bar" "2_bar_n" "1"
  t "2_foo_bar" "2_foo_bar" ""
  t "2_foo_bar" "2_foo_foo" "2"
  t "2_foo_bar" "2_foo_n" "2"
  t "2_foo_bar" "2_n_bar" "1"
  t "2_foo_bar" "2_n_foo" "1"
  t "2_foo_bar" "2_n_n" "1"
  t "2_foo_bar" "3_n_bar_bar" "1"
  t "2_foo_bar" "3_n_bar_foo" "1"
  t "2_foo_bar" "3_n_bar_n" "1"
  t "2_foo_bar" "3_n_foo_bar" "1"
  t "2_foo_bar" "3_n_foo_foo" "1"
  t "2_foo_bar" "3_n_foo_n" "1"
  t "2_foo_bar" "3_n_n_bar" "1"
  t "2_foo_bar" "3_n_n_foo" "1"
  t "2_foo_bar" "3_n_n_n" "1"
}

it_test_2_foo_foo() {
  t "2_foo_foo" "0_empty" "1"
  t "2_foo_foo" "1_bar" "1"
  t "2_foo_foo" "1_foo" "1"
  t "2_foo_foo" "1_n" "1"
  t "2_foo_foo" "2_bar_bar" "1"
  t "2_foo_foo" "2_bar_foo" "1"
  t "2_foo_foo" "2_bar_n" "1"
  t "2_foo_foo" "2_foo_bar" "2"
  t "2_foo_foo" "2_foo_foo" ""
  t "2_foo_foo" "2_foo_n" "2"
  t "2_foo_foo" "2_n_bar" "1"
  t "2_foo_foo" "2_n_foo" "1"
  t "2_foo_foo" "2_n_n" "1"
  t "2_foo_foo" "3_n_bar_bar" "1"
  t "2_foo_foo" "3_n_bar_foo" "1"
  t "2_foo_foo" "3_n_bar_n" "1"
  t "2_foo_foo" "3_n_foo_bar" "1"
  t "2_foo_foo" "3_n_foo_foo" "1"
  t "2_foo_foo" "3_n_foo_n" "1"
  t "2_foo_foo" "3_n_n_bar" "1"
  t "2_foo_foo" "3_n_n_foo" "1"
  t "2_foo_foo" "3_n_n_n" "1"
}

it_test_2_foo_n() {
  t "2_foo_n" "0_empty" "1"
  t "2_foo_n" "1_bar" "1"
  t "2_foo_n" "1_foo" "1"
  t "2_foo_n" "1_n" "1"
  t "2_foo_n" "2_bar_bar" "1"
  t "2_foo_n" "2_bar_foo" "1"
  t "2_foo_n" "2_bar_n" "1"
  t "2_foo_n" "2_foo_bar" "2"
  t "2_foo_n" "2_foo_foo" "2"
  t "2_foo_n" "2_foo_n" ""
  t "2_foo_n" "2_n_bar" "1"
  t "2_foo_n" "2_n_foo" "1"
  t "2_foo_n" "2_n_n" "1"
  t "2_foo_n" "3_n_bar_bar" "1"
  t "2_foo_n" "3_n_bar_foo" "1"
  t "2_foo_n" "3_n_bar_n" "1"
  t "2_foo_n" "3_n_foo_bar" "1"
  t "2_foo_n" "3_n_foo_foo" "1"
  t "2_foo_n" "3_n_foo_n" "1"
  t "2_foo_n" "3_n_n_bar" "1"
  t "2_foo_n" "3_n_n_foo" "1"
  t "2_foo_n" "3_n_n_n" "1"
}

it_test_2_n_bar() {
  t "2_n_bar" "0_empty" "1"
  t "2_n_bar" "1_bar" "1"
  t "2_n_bar" "1_foo" "1"
  t "2_n_bar" "1_n" "2"
  t "2_n_bar" "2_bar_bar" "1"
  t "2_n_bar" "2_bar_foo" "1"
  t "2_n_bar" "2_bar_n" "1"
  t "2_n_bar" "2_foo_bar" "1"
  t "2_n_bar" "2_foo_foo" "1"
  t "2_n_bar" "2_foo_n" "1"
  t "2_n_bar" "2_n_bar" ""
  t "2_n_bar" "2_n_foo" "2"
  t "2_n_bar" "2_n_n" "2"
  t "2_n_bar" "3_n_bar_bar" "2"
  t "2_n_bar" "3_n_bar_foo" "2"
  t "2_n_bar" "3_n_bar_n" "2"
  t "2_n_bar" "3_n_foo_bar" "2"
  t "2_n_bar" "3_n_foo_foo" "2"
  t "2_n_bar" "3_n_foo_n" "2"
  t "2_n_bar" "3_n_n_bar" "2"
  t "2_n_bar" "3_n_n_foo" "2"
  t "2_n_bar" "3_n_n_n" "2"
}

it_test_2_n_foo() {
  t "2_n_foo" "0_empty" "1"
  t "2_n_foo" "1_bar" "1"
  t "2_n_foo" "1_foo" "1"
  t "2_n_foo" "1_n" "2"
  t "2_n_foo" "2_bar_bar" "1"
  t "2_n_foo" "2_bar_foo" "1"
  t "2_n_foo" "2_bar_n" "1"
  t "2_n_foo" "2_foo_bar" "1"
  t "2_n_foo" "2_foo_foo" "1"
  t "2_n_foo" "2_foo_n" "1"
  t "2_n_foo" "2_n_bar" "2"
  t "2_n_foo" "2_n_foo" ""
  t "2_n_foo" "2_n_n" "2"
  t "2_n_foo" "3_n_bar_bar" "2"
  t "2_n_foo" "3_n_bar_foo" "2"
  t "2_n_foo" "3_n_bar_n" "2"
  t "2_n_foo" "3_n_foo_bar" "2"
  t "2_n_foo" "3_n_foo_foo" "2"
  t "2_n_foo" "3_n_foo_n" "2"
  t "2_n_foo" "3_n_n_bar" "2"
  t "2_n_foo" "3_n_n_foo" "2"
  t "2_n_foo" "3_n_n_n" "2"
}

it_test_2_n_n() {
  t "2_n_n" "0_empty" "1"
  t "2_n_n" "1_bar" "1"
  t "2_n_n" "1_foo" "1"
  t "2_n_n" "1_n" "2"
  t "2_n_n" "2_bar_bar" "1"
  t "2_n_n" "2_bar_foo" "1"
  t "2_n_n" "2_bar_n" "1"
  t "2_n_n" "2_foo_bar" "1"
  t "2_n_n" "2_foo_foo" "1"
  t "2_n_n" "2_foo_n" "1"
  t "2_n_n" "2_n_bar" "2"
  t "2_n_n" "2_n_foo" "2"
  t "2_n_n" "2_n_n" ""
  t "2_n_n" "3_n_bar_bar" "2"
  t "2_n_n" "3_n_bar_foo" "2"
  t "2_n_n" "3_n_bar_n" "2"
  t "2_n_n" "3_n_foo_bar" "2"
  t "2_n_n" "3_n_foo_foo" "2"
  t "2_n_n" "3_n_foo_n" "2"
  t "2_n_n" "3_n_n_bar" "3"
  t "2_n_n" "3_n_n_foo" "3"
  t "2_n_n" "3_n_n_n" "3"
}

it_test_3_n_bar_bar() {
  t "3_n_bar_bar" "0_empty" "1"
  t "3_n_bar_bar" "1_bar" "1"
  t "3_n_bar_bar" "1_foo" "1"
  t "3_n_bar_bar" "1_n" "2"
  t "3_n_bar_bar" "2_bar_bar" "1"
  t "3_n_bar_bar" "2_bar_foo" "1"
  t "3_n_bar_bar" "2_bar_n" "1"
  t "3_n_bar_bar" "2_foo_bar" "1"
  t "3_n_bar_bar" "2_foo_foo" "1"
  t "3_n_bar_bar" "2_foo_n" "1"
  t "3_n_bar_bar" "2_n_bar" "2"
  t "3_n_bar_bar" "2_n_foo" "2"
  t "3_n_bar_bar" "2_n_n" "2"
  t "3_n_bar_bar" "3_n_bar_bar" ""
  t "3_n_bar_bar" "3_n_bar_foo" "3"
  t "3_n_bar_bar" "3_n_bar_n" "3"
  t "3_n_bar_bar" "3_n_foo_bar" "2"
  t "3_n_bar_bar" "3_n_foo_foo" "2"
  t "3_n_bar_bar" "3_n_foo_n" "2"
  t "3_n_bar_bar" "3_n_n_bar" "2"
  t "3_n_bar_bar" "3_n_n_foo" "2"
  t "3_n_bar_bar" "3_n_n_n" "2"
}

it_test_3_n_bar_foo() {
  t "3_n_bar_foo" "0_empty" "1"
  t "3_n_bar_foo" "1_bar" "1"
  t "3_n_bar_foo" "1_foo" "1"
  t "3_n_bar_foo" "1_n" "2"
  t "3_n_bar_foo" "2_bar_bar" "1"
  t "3_n_bar_foo" "2_bar_foo" "1"
  t "3_n_bar_foo" "2_bar_n" "1"
  t "3_n_bar_foo" "2_foo_bar" "1"
  t "3_n_bar_foo" "2_foo_foo" "1"
  t "3_n_bar_foo" "2_foo_n" "1"
  t "3_n_bar_foo" "2_n_bar" "2"
  t "3_n_bar_foo" "2_n_foo" "2"
  t "3_n_bar_foo" "2_n_n" "2"
  t "3_n_bar_foo" "3_n_bar_bar" "3"
  t "3_n_bar_foo" "3_n_bar_foo" ""
  t "3_n_bar_foo" "3_n_bar_n" "3"
  t "3_n_bar_foo" "3_n_foo_bar" "2"
  t "3_n_bar_foo" "3_n_foo_foo" "2"
  t "3_n_bar_foo" "3_n_foo_n" "2"
  t "3_n_bar_foo" "3_n_n_bar" "2"
  t "3_n_bar_foo" "3_n_n_foo" "2"
  t "3_n_bar_foo" "3_n_n_n" "2"
}

it_test_3_n_bar_n() {
  t "3_n_bar_n" "0_empty" "1"
  t "3_n_bar_n" "1_bar" "1"
  t "3_n_bar_n" "1_foo" "1"
  t "3_n_bar_n" "1_n" "2"
  t "3_n_bar_n" "2_bar_bar" "1"
  t "3_n_bar_n" "2_bar_foo" "1"
  t "3_n_bar_n" "2_bar_n" "1"
  t "3_n_bar_n" "2_foo_bar" "1"
  t "3_n_bar_n" "2_foo_foo" "1"
  t "3_n_bar_n" "2_foo_n" "1"
  t "3_n_bar_n" "2_n_bar" "2"
  t "3_n_bar_n" "2_n_foo" "2"
  t "3_n_bar_n" "2_n_n" "2"
  t "3_n_bar_n" "3_n_bar_bar" "3"
  t "3_n_bar_n" "3_n_bar_foo" "3"
  t "3_n_bar_n" "3_n_bar_n" ""
  t "3_n_bar_n" "3_n_foo_bar" "2"
  t "3_n_bar_n" "3_n_foo_foo" "2"
  t "3_n_bar_n" "3_n_foo_n" "2"
  t "3_n_bar_n" "3_n_n_bar" "2"
  t "3_n_bar_n" "3_n_n_foo" "2"
  t "3_n_bar_n" "3_n_n_n" "2"
}

it_test_3_n_foo_bar() {
  t "3_n_foo_bar" "0_empty" "1"
  t "3_n_foo_bar" "1_bar" "1"
  t "3_n_foo_bar" "1_foo" "1"
  t "3_n_foo_bar" "1_n" "2"
  t "3_n_foo_bar" "2_bar_bar" "1"
  t "3_n_foo_bar" "2_bar_foo" "1"
  t "3_n_foo_bar" "2_bar_n" "1"
  t "3_n_foo_bar" "2_foo_bar" "1"
  t "3_n_foo_bar" "2_foo_foo" "1"
  t "3_n_foo_bar" "2_foo_n" "1"
  t "3_n_foo_bar" "2_n_bar" "2"
  t "3_n_foo_bar" "2_n_foo" "2"
  t "3_n_foo_bar" "2_n_n" "2"
  t "3_n_foo_bar" "3_n_bar_bar" "2"
  t "3_n_foo_bar" "3_n_bar_foo" "2"
  t "3_n_foo_bar" "3_n_bar_n" "2"
  t "3_n_foo_bar" "3_n_foo_bar" ""
  t "3_n_foo_bar" "3_n_foo_foo" "3"
  t "3_n_foo_bar" "3_n_foo_n" "3"
  t "3_n_foo_bar" "3_n_n_bar" "2"
  t "3_n_foo_bar" "3_n_n_foo" "2"
  t "3_n_foo_bar" "3_n_n_n" "2"
}

it_test_3_n_foo_foo() {
  t "3_n_foo_foo" "0_empty" "1"
  t "3_n_foo_foo" "1_bar" "1"
  t "3_n_foo_foo" "1_foo" "1"
  t "3_n_foo_foo" "1_n" "2"
  t "3_n_foo_foo" "2_bar_bar" "1"
  t "3_n_foo_foo" "2_bar_foo" "1"
  t "3_n_foo_foo" "2_bar_n" "1"
  t "3_n_foo_foo" "2_foo_bar" "1"
  t "3_n_foo_foo" "2_foo_foo" "1"
  t "3_n_foo_foo" "2_foo_n" "1"
  t "3_n_foo_foo" "2_n_bar" "2"
  t "3_n_foo_foo" "2_n_foo" "2"
  t "3_n_foo_foo" "2_n_n" "2"
  t "3_n_foo_foo" "3_n_bar_bar" "2"
  t "3_n_foo_foo" "3_n_bar_foo" "2"
  t "3_n_foo_foo" "3_n_bar_n" "2"
  t "3_n_foo_foo" "3_n_foo_bar" "3"
  t "3_n_foo_foo" "3_n_foo_foo" ""
  t "3_n_foo_foo" "3_n_foo_n" "3"
  t "3_n_foo_foo" "3_n_n_bar" "2"
  t "3_n_foo_foo" "3_n_n_foo" "2"
  t "3_n_foo_foo" "3_n_n_n" "2"
}

it_test_3_n_foo_n() {
  t "3_n_foo_n" "0_empty" "1"
  t "3_n_foo_n" "1_bar" "1"
  t "3_n_foo_n" "1_foo" "1"
  t "3_n_foo_n" "1_n" "2"
  t "3_n_foo_n" "2_bar_bar" "1"
  t "3_n_foo_n" "2_bar_foo" "1"
  t "3_n_foo_n" "2_bar_n" "1"
  t "3_n_foo_n" "2_foo_bar" "1"
  t "3_n_foo_n" "2_foo_foo" "1"
  t "3_n_foo_n" "2_foo_n" "1"
  t "3_n_foo_n" "2_n_bar" "2"
  t "3_n_foo_n" "2_n_foo" "2"
  t "3_n_foo_n" "2_n_n" "2"
  t "3_n_foo_n" "3_n_bar_bar" "2"
  t "3_n_foo_n" "3_n_bar_foo" "2"
  t "3_n_foo_n" "3_n_bar_n" "2"
  t "3_n_foo_n" "3_n_foo_bar" "3"
  t "3_n_foo_n" "3_n_foo_foo" "3"
  t "3_n_foo_n" "3_n_foo_n" ""
  t "3_n_foo_n" "3_n_n_bar" "2"
  t "3_n_foo_n" "3_n_n_foo" "2"
  t "3_n_foo_n" "3_n_n_n" "2"
}

it_test_3_n_n_bar() {
  t "3_n_n_bar" "0_empty" "1"
  t "3_n_n_bar" "1_bar" "1"
  t "3_n_n_bar" "1_foo" "1"
  t "3_n_n_bar" "1_n" "2"
  t "3_n_n_bar" "2_bar_bar" "1"
  t "3_n_n_bar" "2_bar_foo" "1"
  t "3_n_n_bar" "2_bar_n" "1"
  t "3_n_n_bar" "2_foo_bar" "1"
  t "3_n_n_bar" "2_foo_foo" "1"
  t "3_n_n_bar" "2_foo_n" "1"
  t "3_n_n_bar" "2_n_bar" "2"
  t "3_n_n_bar" "2_n_foo" "2"
  t "3_n_n_bar" "2_n_n" "3"
  t "3_n_n_bar" "3_n_bar_bar" "2"
  t "3_n_n_bar" "3_n_bar_foo" "2"
  t "3_n_n_bar" "3_n_bar_n" "2"
  t "3_n_n_bar" "3_n_foo_bar" "2"
  t "3_n_n_bar" "3_n_foo_foo" "2"
  t "3_n_n_bar" "3_n_foo_n" "2"
  t "3_n_n_bar" "3_n_n_bar" ""
  t "3_n_n_bar" "3_n_n_foo" "3"
  t "3_n_n_bar" "3_n_n_n" "3"
}

it_test_3_n_n_foo() {
  t "3_n_n_foo" "0_empty" "1"
  t "3_n_n_foo" "1_bar" "1"
  t "3_n_n_foo" "1_foo" "1"
  t "3_n_n_foo" "1_n" "2"
  t "3_n_n_foo" "2_bar_bar" "1"
  t "3_n_n_foo" "2_bar_foo" "1"
  t "3_n_n_foo" "2_bar_n" "1"
  t "3_n_n_foo" "2_foo_bar" "1"
  t "3_n_n_foo" "2_foo_foo" "1"
  t "3_n_n_foo" "2_foo_n" "1"
  t "3_n_n_foo" "2_n_bar" "2"
  t "3_n_n_foo" "2_n_foo" "2"
  t "3_n_n_foo" "2_n_n" "3"
  t "3_n_n_foo" "3_n_bar_bar" "2"
  t "3_n_n_foo" "3_n_bar_foo" "2"
  t "3_n_n_foo" "3_n_bar_n" "2"
  t "3_n_n_foo" "3_n_foo_bar" "2"
  t "3_n_n_foo" "3_n_foo_foo" "2"
  t "3_n_n_foo" "3_n_foo_n" "2"
  t "3_n_n_foo" "3_n_n_bar" "3"
  t "3_n_n_foo" "3_n_n_foo" ""
  t "3_n_n_foo" "3_n_n_n" "3"
}

it_test_3_n_n_n() {
  t "3_n_n_n" "0_empty" "1"
  t "3_n_n_n" "1_bar" "1"
  t "3_n_n_n" "1_foo" "1"
  t "3_n_n_n" "1_n" "2"
  t "3_n_n_n" "2_bar_bar" "1"
  t "3_n_n_n" "2_bar_foo" "1"
  t "3_n_n_n" "2_bar_n" "1"
  t "3_n_n_n" "2_foo_bar" "1"
  t "3_n_n_n" "2_foo_foo" "1"
  t "3_n_n_n" "2_foo_n" "1"
  t "3_n_n_n" "2_n_bar" "2"
  t "3_n_n_n" "2_n_foo" "2"
  t "3_n_n_n" "2_n_n" "3"
  t "3_n_n_n" "3_n_bar_bar" "2"
  t "3_n_n_n" "3_n_bar_foo" "2"
  t "3_n_n_n" "3_n_bar_n" "2"
  t "3_n_n_n" "3_n_foo_bar" "2"
  t "3_n_n_n" "3_n_foo_foo" "2"
  t "3_n_n_n" "3_n_foo_n" "2"
  t "3_n_n_n" "3_n_n_bar" "3"
  t "3_n_n_n" "3_n_n_foo" "3"
  t "3_n_n_n" "3_n_n_n" ""
}
