language: sh

before_script:
  - chmod +x diff-line
  - curl -sS -o test/roundup https://raw.githubusercontent.com/bmizerany/roundup/a8a175a7fba9bbfb14d1025951c4b46a65e875a6/roundup.sh
  - chmod +x test/roundup

script:
  - cd test && ./roundup
